// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsggtrttmxfxnyttykts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzZ2d0cnR0bXhmeG55dHR5a3RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDAyMjIsImV4cCI6MjA2NTQ3NjIyMn0.e79LKx-a07y9-4dkzK1kX26txP69bcJ5Zt34hUNbuJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);